Fix invalid `<os>` dependency in package.xml
Only a single name is allowed.

See https://github.com/pear/pear-core/blob/v1.10.14/PEAR/Dependency2.php#L214

`unix` is short for: 'linux', 'freebsd', 'darwin', 'sunos', 'irix',
'hpux', and 'aix'.

Follows-up 4cc649be12 (I553b3a81af), which caused a failure during
installation:

```
Fatal error: Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given
Stack trace:
pear/PEAR/Dependency2.php(194): strtolower(Array)
pear/PEAR/Downloader.php(582): PEAR_Dependency2->validateOsDependency(Array, true, Array)
pear/PEAR/Downloader.php(458): PEAR_Downloader->analyzeDependencies(Array)
pear/PEAR/Command/Install.php(671): PEAR_Downloader->download(Array)
pear/PEAR/Command/Common.php(270): PEAR_Command_Install->doInstall('install', Array, Array)
```

Change-Id: I90280fe96120ac93d0a211918fd0b325d27d0361